title: Web Engineering 
description: Web engineering course pages on GitHub
show_downloads: false
theme: jekyll-theme-dinky
header_pages:
  - main-it.md
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
