title: Web Engineering course pages
theme: minima
header_pages:
  - main-it.md
author:
  name: Giuseppe Della Penna
  email: "giuseppe.dellapenna@univaq.it"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
