title: Web Engineering
description: Web Engineering course pages, University of L'Aquila
course: Web Engineering
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"